# Generated by Django 5.0.2 on 2024-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='freeSpace',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='totalSpace',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='usedSpace',
            field=models.IntegerField(),
        ),
    ]
